version: "3.8"

services:
  app:
    build: .
    container_name: cloudnest_app
    restart: always

  nginx:
    image: nginx:latest
    container_name: cloudnest_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/cloudnest.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
